### ISSUE TITLE
ProjectSettings shouldn't be in gitignored

### ISSUE THREAD

**Issue by andybak** [hxsgz/UnityDanMuTutorial#1]
https://github.com/hxsgz/UnityDanMuTutorial/blob/cbd57740fc894b523c14c5a28dc6ddacb0752848/.gitignore#L61

At least I've never come across a reason for it to be. The lack of ProjectVersion.txt is the most noticeable drawback.

**Comment by hxsgz** [comment]
yeah  you are right , i will delete it at next push

**Comment by hxsgz** [comment]
commit
